# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_num', models.IntegerField()),
                ('doc_type', models.CharField(max_length=50)),
                ('time_published', models.DateTimeField()),
                ('is_main', models.BooleanField(default=False)),
                ('path_html', models.CharField(max_length=500)),
                ('path_pdf', models.CharField(max_length=500)),
                ('xhtml', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_num', models.IntegerField()),
                ('issue_type', models.CharField(choices=[('l', 'lagafrumvarp'), ('a', 'þingsályktunartillaga'), ('m', 'fyrirspurn'), ('q', 'fyrirspurn til skrifl. svars')], max_length=1)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_num', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='althingi.Session'),
        ),
        migrations.AddField(
            model_name='document',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='althingi.Issue'),
        ),
    ]
