# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('resource', models.CharField(max_length=500)),
                ('external_id', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('positive_notion', models.BooleanField(default=False)),
                ('time_published', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-time_published', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('stance', models.CharField(max_length=50)),
                ('show_public', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('mail_sent', models.BooleanField(default=False)),
                ('authentication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.UserAuthentication')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.Petition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='petition',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.Source'),
        ),
    ]
